---
name: array-of-lb
namespace: com.citrix.adc.stylebooks
version: "1.0"
display-name: "List of LoadBalancers"
description: "List of LoadBalancers"
schema-version: "1.0"
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    prefix: ns
    version: "10.5"

parameters:
  - 
    name: app-services
    label: "LB Settings"
    description: "Settings for all the Load Balancers"
    type: object[]
    required: true
    parameters:
      - 
        name: appname
        label: "Load Balanced Application Name"
        description: "Load Balanced Application Name"
        type: string
        required: true
      - 
        name: virtual-ip
        label: "Load Balanced App Virtual IP address"
        description: "Virtual IP address representing the Load Balanced application"
        type: ipaddress
        required: true
      - 
        name: virtual-port
        label: "Load Balanced App Virtual Port"
        description: "TCP port representing the Load Balanced application"
        type: tcp-port
        required: true
        default: 80
substitutions:
  lb-name(appname, port): $appname + "-" + str($port) + "-lb"
  sg-name(appname, port): $appname + "-" + str($port) + "-sg"
  healthmonitor[]:
    true: "NO"
    false: "YES"
components: 
  - 
    name: lb-comp
    type: ns::lbvserver
    repeat: $parameters.app-services
    repeat-item: app
    properties: 
      name: $substitutions.lb-name($app.appname, $app.virtual-port)
      ipv46: $app.virtual-ip
      port: $app.virtual-port
      servicetype: HTTP
      
      