--- 
components: 
  - 
    components: 
      - 
        name: my-lbvserver-comp
        properties: 
          ipv46: "192.168.1.1"
          name: a1
          port: 80
          servicetype: HTTP
        type: "ns::lbvserver"
    name: my-csvserver-comp
    properties: 
      ipv46: $parameters.cs-params.vip-params.vip
      name: $parameters.cs-params.csname
      port: 80
      servicetype: HTTP
    type: "ns::csvserver"
  - 
    name: my-lbvserver-comp
    properties: 
      ipv46: $vs.vip
      lbmethod: $vs.lbmethod
      name: $vs.lbname
      port: 80
      servicetype: HTTP
    repeat: $parameters.vip-params
    repeat-item: vs
    type: "ns::lbvserver"
description: "This stylebook defines an example operations component."
display-name: "SB Operations (LB & CS)"
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    prefix: ns
    version: "10.5"
name: example-analytics-only
namespace: com.acme.stylebooks
operations: 
  analytics: 
    - 
      name: csvserver-op
      properties: 
        filter: $parameters.appflowfilter
        insights: 
          - 
            type: securityinsight
        target: $outputs.mycs
outputs: 
  - 
    name: mycs
    value: $components.my-csvserver-comp
  - 
    name: mylbs
    value: $components.my-lbvserver-comp
parameters: 
  - 
    name: cs-params
    parameters: 
      - 
        name: csname
        required: true
        type: string
      - 
        name: vip-params
        parameters: 
          - 
            name: vip
            required: true
            type: ipaddress
        required: true
        type: object
    required: true
    type: object
  - 
    name: appflowfilter
    required: true
    type: string
  - 
    name: emailprofile
    required: true
    type: string
  - 
    name: period
    required: true
    type: string
  - 
    name: vip-params
    parameters: 
      - 
        name: lbname
        required: true
        type: string
      - 
        name: vip
        required: true
        type: ipaddress
      - 
        name: lbmethod
        required: true
        type: string
    required: true
    type: "object[]"
schema-version: "1.0"
substitutions: 
  analytics_object_cstype: csvserver
  analytics_object_lbtype: lbvserver
version: "0.1"