--- 
name: cs-lbs-binds
namespace: com.citrix.adc.stylebooks
version: "1.0"
description: "This StyleBook is defined to create and bind a set of CS Policies to an existing CS Vserver."
private: true
schema-version: "1.0"
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    prefix: ns
    version: "10.5"
  - 
    namespace: com.citrix.adc.commontypes
    prefix: cmtypes
    version: "1.0"
  - 
    namespace: com.citrix.adc.stylebooks
    prefix: stlb
    version: "1.0"
substitutions: 
  cs-actionname(poolname): $parameters.csvserver-name + "-" + $poolname + "-csaction"
  cs-policyname(poolname): $parameters.csvserver-name + "-" + $poolname + "-cspol"
  cspol-priority(priority): "10100 - 100 * int($priority)"
  lbname-from-poolname(poolname): $parameters.csvserver-name + "-" + $poolname + "-lb"
parameters: 
  - 
    name: csvserver-name
    description: "Name of the Content Switched application to which policies are bound"
    label: "Content Switched App Name"
    type: string
    key: true
    required: true
    updatable: true
  - 
    name: default-lbvserver-name
    label: "Content Switch App Server Default LB VServer"
    description: "Details of the Default LBVServer for this application."
    type: string
    required: true
    updatable: true
  - 
    name: pools
    label: "Server Pools"
    description: "Details of other Server pools for this application."
    type: "cmtypes::cs-pool[]"
    required: false
    updatable: true
components: 
  - 
    name: cs-defaultlb-bind-comp
    type: ns::csvserver_lbvserver_binding
    description: "This component binds the default LB vserver to the CS vserver"
    properties: 
      name: $parameters.csvserver-name
      lbvserver: $parameters.default-lbvserver-name
  - 
    name: csactions-comp
    type: ns::csaction 
    condition: $parameters.pools
    repeat: $parameters.pools
    repeat-item: pool
    properties: 
      name: $substitutions.cs-actionname($pool.lb-pool.lb-appname)
      targetlbvserver: $substitutions.lbname-from-poolname($pool.lb-pool.lb-appname)
  - 
    name: cspolicies-comp
    type: ns::cspolicy
    condition: $parameters.pools
    repeat: $parameters.pools
    repeat-item: pool
    properties: 
      action: $substitutions.cs-actionname($pool.lb-pool.lb-appname)
      policyname: $substitutions.cs-policyname($pool.lb-pool.lb-appname)
      rule: $pool.rule
  - 
    name: cspolicy-bindings-comp
    type: ns::csvserver_cspolicy_binding  
    condition: "$parameters.pools and $components.cspolicies-comp"
    repeat: $parameters.pools
    repeat-item: pool
    properties: 
      name: $parameters.csvserver-name
      policyname: $substitutions.cs-policyname($pool.lb-pool.lb-appname)
      priority: $substitutions.cspol-priority($pool.priority)
outputs: 
  - 
    name: cs-defaultlb-bind 
    description: "Exposes the default load balanced virtual server"
    value: $components.cs-defaultlb-bind-comp
  - 
    name: cs-lbpols-binds
    description: "Exposes the created CS policies bindings"
    value: $components.cspolicy-bindings-comp
