#
# ref : GLaaS-TP1-CSVServer-Policies-Binding-StyleBook
# Copyright 2016 Citrix Systems, Inc. All rights reserved.
# This software and documentation contain valuable trade
# secrets and proprietary property belonging to Citrix Systems, Inc.
# None of this software and documentation may be copied,
# duplicated or disclosed without the express
# written permission of Citrix Systems, Inc.
#
--- 
name: GLaaS-CS-VIP-POL_BIND-StyleBook
description: "ThisiGLaaS stylebook is defined to create and bind a set of CS Policies to an existing CS Vserver."
namespace: com.citrix.adc.stylebooks
schema-version: "1.0"
version: "1.1"
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    prefix: ns
    version: "10.5"
parameters: 
  - 
    name: appname
    description: "Name of the Content Switched application to which policies are bound"
    label: "Content Switched App Name"
    type: string
    key: true
    required: true
    updatable: true
  -
    name: index
    description: "Index"
    type: number
    required: true
    updatable: false
  - 
    name: pools
    label: "Server Pools"
    description: "Details of other server pools for the content switched application."
    type: "object[]"
    required: false
    updatable: true
    parameters: 
      - 
        name: poolname
        label: "Server Pool Name"
        description: "Name of additional server pool"
        type: string
        required: true
        updatable: true
        gui: 
          summary_display: true
      - 
        name: svc-servers
        label: "Application Servers IP Addresses"
        description: "List of the IP addresses of the application servers that are members of this server pool."
        type: "ipaddress[]"
        required: true
        updatable: true
      - 
        name: svc-server-port
        label: "Application Server Port"
        description: "TCP port of the application servers"
        type: tcp-port
        required: true
        updatable: false
        default: 53
      -
        name: domain-names
        label: "Domain Names"
        type: string[]
        required: false
        updatable: true
      - 
        name: priority
        label: "Priority"
        description: "Priority of this L7 rule. The higher the number, the more prioritized the rule."
        type: number
        max-value: 100
        min-value: 1
        required: true
        updatable: false 
        gui: 
          summary_display: true
substitutions: 
  cs-actionname(poolname): $parameters.appname + "_" + $poolname + "_" + str($parameters.index) + "_csaction"
  cs-policyname(poolname): $parameters.appname + "_" + $poolname + "_" + str($parameters.index) + "_cspol"
  cspol-priority(priority): 10100 - 100 * int($priority)
  csvserver-name: $parameters.appname + "_" + str($parameters.index) + "_cs"
  lbname-from-poolname(poolname): $parameters.appname + "_" + $poolname + "_" + str($parameters.index) + "_lb"
  cs-rule(poolname): str("DNS.REQ.QUESTION.DOMAIN.CONTAINS_ANY(\"") + str($parameters.appname) + "_" + str($poolname) + str("_") + str($parameters.index) + str("_patset\")")
components: 
  - 
    name: csactions-comp
    type: "ns::csaction"    
    condition: $parameters.pools
    repeat: $parameters.pools
    repeat-item: pool
    properties: 
      name: $substitutions.cs-actionname($pool.poolname)
      targetlbvserver: $substitutions.lbname-from-poolname($pool.poolname)
  - 
    name: cspolicies-comp
    type: "ns::cspolicy"
    condition: $parameters.pools
    repeat: $parameters.pools
    repeat-item: pool
    properties: 
      action: $substitutions.cs-actionname($pool.poolname)
      policyname: $substitutions.cs-policyname($pool.poolname)
      rule: $substitutions.cs-rule($pool.poolname)
  - 
    name: cspolicy_binding
    type: "ns::csvserver_cspolicy_binding"    
    condition: "$parameters.pools and $components.cspolicies-comp"
    repeat: $parameters.pools
    repeat-item: pool
    properties: 
      name: $substitutions.csvserver-name
      policyname: $substitutions.cs-policyname($pool.poolname)
      priority: $substitutions.cspol-priority($pool.priority)
outputs: 
  - 
    name: cspolicies_bindings
    description: "Exposes the created CS policies bindings"
    value: $components.cspolicy_binding
