
#
# ref : GLaaS-TP1-CS-HTTP-LB-MON-StyleBook
# Copyright 2016 Citrix Systems, Inc. All rights reserved.
# This software and documentation contain valuable trade
# secrets and proprietary property belonging to Citrix Systems, Inc.
# None of this software and documentation may be copied,
# duplicated or disclosed without the express
# written permission of Citrix Systems, Inc.
#
--- 
name: GLaaS-CS-DNS-TT-StyleBook
display-name: "GLaaS - Content Switched Applications (DNS)"
description: "This network function defines a typical GLaaS DNS/DNS_TCP Content Switched Application configuration."
namespace: com.citrix.adc.stylebooks
schema-version: "1.0"
version: "1.1"
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    prefix: ns
    version: "10.5"
  - 
    namespace: com.citrix.adc.stylebooks
    prefix: stlb
    version: "1.1"
substitutions: 
  cspol-priority(priority): 10100 - 100 * $priority
  lbname-from-poolname(poolname): $parameters.appname + "-" + $poolname
parameters: 
  - 
    name: appname
    label: "Content Switched App Name"
    description: "Name of the content switched application."
    type: string
    key: true
    required: true
    updatable: true
  - 
    name: virtual-ip
    label: "Content Switched App IP Address"
    description: "Public Virtual IP address of the content switched application."
    type: ipaddress
    required: true
    updatable: false
  - 
    name: virtual-port
    label: "Load Balanced App Virtual Port"
    description: "Public port representing the Load Balanced application"
    type: tcp-port
    required: true
    updatable: false
    default: 53     
  -
    name: protocols
    label: "Protocols"
    description: "Protocols"
    type: string[]
    required: true
    updatable: false
    allowed-values:
      - "DNS"
      - "DNS_TCP"
  -
    name: pools
    label: "Server Pools"
    description: "Details of other server pools for the content switched application."
    type: "object[]"
    required: false
    updatable: true
    parameters: 
      - 
        name: poolname
        label: "Server Pool Name"
        description: "Name of additional server pool"
        type: string
        required: true
        updatable: true
        gui: 
          summary_display: true
      - 
        name: svc-servers
        label: "Application Servers IP Addresses"
        description: "List of the IP addresses of the application servers that are members of this server pool."
        type: "ipaddress[]"
        required: true
        updatable: true
      - 
        name: svc-server-port
        label: "Application Server Port"
        description: "TCP port of the application servers"
        type: tcp-port
        required: true
        updatable: false
        default: 53
      -
        name: domain-names
        label: "Domain Names"
        type: string[]
        required: false
        updatable: true
      - 
        name: priority
        label: "Priority"
        description: "Priority of this L7 rule. The higher the number, the more prioritized the rule."
        type: number
        max-value: 100
        min-value: 1
        required: true
        updatable: false 
        gui: 
          summary_display: true
components: 
  - 
    name: dns-lb-vip
    type: stlb::GLaaS-DNS-PATSET-StyleBook
    description: "This list of components are used to generate LB Vservers for all the pools used in Content Switching (L7 rules supplied in parameters)"
    condition: $parameters.pools
    repeat: $parameters.pools
    repeat-item: pool
    properties: 
      appname: $parameters.appname + "_" + $pool.poolname
      lb-advanced: 
        dns-virtual-port: 0
      dns-virtual-ip: "0.0.0.0"
      svc-server-port: $pool.svc-server-port
      svc-servers: $pool.svc-servers
      dns-servicetype : $parameters.protocols
      domain-names: $pool.domain-names
  - 
    name: csvserver-comp
    type: "ns::csvserver"
    repeat: $parameters.protocols
    repeat-item: dnsproto 
    repeat-index: index
    properties: 
      ipv46: $parameters.virtual-ip
      name: $parameters.appname + "_" + str($index) + "_cs"
      port: $parameters.virtual-port
      servicetype: $dnsproto
    components: 
      - 
        name: csvserver-policies
        type: "stlb::GLaaS-CS-VIP-POL_BIND-StyleBook"           
        description: "This component is used to create and bind CS Policies to the CS vserver"
        properties: 
          appname: $parameters.appname
          pools: $parameters.pools
          index: $index
outputs: 
  - 
    name: csvserver
    value: $components.csvserver-comp
    description: "Exposes the created CS vserver component"
