---
name: lb-app-b
description: "This stylebook defines a simple lbvserver"
display-name: "LBVserver (HTTP)"
namespace: com.acme.stylebooks
schema-version: "1.0"
builtin: true
version: "0.1"
import-stylebooks:
 -
  namespace: netscaler.nitro.config
  prefix: ns
  version: "10.5"
parameters:
 -
  name: lbvserver-name
  type: string
 -
  name: port
  type: number
 -
  name: lb-vip
  type: ipaddress
 -
  name: lbmethod
  type: string
  default: LEASTCONNECTION
  allowed-values:
    - ROUNDROBIN
    - LEASTCONNECTION
    - LEASTRESPONSETIME
    - LEASTPACKETS
    - CUSTOMLOAD


substitutions:
  append_app_name(name): $name + "myApp"

components:
 -
  name: my-lbvserver-comp
  type: ns::lbvserver
  properties:
   name: $substitutions.append_app_name($parameters.lbvserver-name)
   servicetype: HTTP
   ipv46: $parameters.lb-vip
   port: $parameters.port
   lbmethod: $parameters.lbmethod
 
outputs:
  -
    name: lbvserver
    value: $components.my-lbvserver-comp
