---
name: simple-lbvserver
description: "This stylebook defines a simple lbvserver"
display-name: "LBVserver (HTTP)"
namespace: com.acme.stylebooks
schema-version: "1.0"
version: "0.1"
import-stylebooks:
 -
  namespace: netscaler.nitro.config
  prefix: ns
  version: "10.5"
parameters:
 -
  name: name
  type: string
 -
  name: port
  type: number
 -
  name: ip
  type: ipaddress

substitutions:
  append_app_name(name): $name + "myApp"

components:
 -
  name: my-lbvserver-comp
  type: ns::lbvserver
  properties:
   name: $substitutions.append_app_name($parameters.name)
   servicetype: HTTP
   ipv46: $parameters.ip
   port: $parameters.port
   lbmethod: ROUNDROBIN
outputs:
  -
    name: lbvserver
    value: $components.my-lbvserver-comp
